<?php

namespace AppBundle\Repository;

use AppBundle\Entity\LottoNumber;
use Doctrine\ORM\EntityRepository;

/**
 * LottoNumberRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LottoNumberRepository extends EntityRepository
{
    public function getNumberZeroFrequency()
    {

        $numbers = $this->_em->getRepository('AppBundle:LottoNumber')->findAll();

        $amount = 0;
        $zeroAmount = 0;

        /** @var LottoNumber $lottoNumber */
        foreach ($numbers as $lottoNumber)
        {
            $amount = $amount + 1;

            $lastDigit = $lottoNumber->getNumber() % 10;

            if ($lastDigit == 0)
            {
                $zeroAmount = $zeroAmount + 1;
            }
        }

        if ($amount == 0)
        {
            return 0;
        }

        return round( $zeroAmount / $amount, 2 ) * 100;
    }
}
