<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\QueryBuilder;


/**
 * LottoNumberRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LottoNumberRepository extends EntityRepository
{
    public function getNumberZeroFrequency()
    {
        $numbers = $this->getDoctrine()->getRepository('AppBundle:LottoNumber')->findAll();
        $numbers = array ('number');

        foreach ($numbers as $number)
        {
            $lastDigit = $number[4];

            if ($lastDigit == 0)
            {
                $countLastDigit = $countLastDigit + 1;
            }
        }

        return $countLastDigit / 100;

    }


}
