<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LottoNumberRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LottoNumberRepository extends EntityRepository
{
    public function getNumberZeroFrequency()
    {
        return 6;
    }


}
