# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
# Sonata Admins
    admin.lotto_number:
        class: AppBundle\Admin\LottoNumberAdmin
        arguments: [ ~, AppBundle\Entity\LottoNumber, ~  ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Lottery Numbers", group: "Web" }

# Sonata Blocks
    admin.block.messages:
        class: AppBundle\Admin\Block\FrequencyBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.messages", "@templating", "@doctrine.orm.entity_manager" ]

parameters:
#    parameter_name: value


