# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
# Sonata Admins
    admin.lotto_number:
        class: AppBundle\Admin\LottoNumberAdmin
        arguments: [ ~, AppBundle\Entity\LottoNumber, ~  ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Lottery Numbers", group: "" }

parameters:
#    parameter_name: value
