# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
# Sonata Admins
    admin.contact:
        class: AppBundle\Admin\LottoNumberAdmin
        arguments: [ ~, AppBundle\Entity\LottoNumber, AppBundle:Admin\LottoNumberAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Lottery Numbers", group: "Web" }


parameters:
#    parameter_name: value
